### ISSUE TITLE
Adicionar gerador de anomalia

### ISSUE THREAD

**Issue by degrecci** [hack-and-slash/gerador-de-goblins-malditos#1]
Uma das características de um goblin é ter algum tipo de anomalia, porém no gerador atual não estamos rodando especificamente qual anomalia o goblin possuí, a ideia é gerarmos randomicamente a partir da tabela abaixo.

2D6 | Anomalia
---- | ------------
3-3 | Manchas rosas
4 | Orelhas no sovaco
5 | Corcunda
6 | Braço extra atrofiado
7 | (1 D6) Olhos
8 | Olhos Gigantes
9 | Mãos Gigantes
10 | Duas Cabeças
11-12 | Role mais 2 vezes

Ps¹: Ao rodar 7 nota-se que será necessário rodas a quantidade de olhos a partir de 1D6 (se cair 2 olhos acaba não sendo uma anomalia 🤔).
Ps²: Ao rolar 11 ou 12 o goblin possuirá mais de uma anomalia, sendo assim, será necessária uma função recursiva.

**Comment by Renato66** [comment]
trabalhando nessa issue

**Comment by Renato66** [comment]
poderia fechar essa issue?
