### ISSUE TITLE
Melhorar descrição de equipamentos

### ISSUE THREAD

**Issue by degrecci** [hack-and-slash/gerador-de-goblins-malditos#2]
Adicionar informação de dano/proteção e descrição, nos equipamentos que já são gerados randomicamente:

Arma | Dano | Descrição
------ | ------ |------
Adaga | 2 | Pode ser arremessado
Arco Simples  | 2
Arco Composto | 3
Besta | 3
Espada | 3
Machado | 4
Machadinha | 3 | Pode ser arremessado
Espadona | 5
Pistola | 4
Galinha explosiva  |  4 | dano em todos até 3m
Barril de Pólvora | 5 | dano em todos até 3m
Canhão |  8 | Carregar [2 turnos]

Equipamento | Proteção
--------------- | ---------
Escudo | 1
Elmo | 1
Armadura | 1

**Comment by Bordotti** [comment]
Realizado o PR com a alteração hardcoded.
Ideia de melhoramento é a troca de estrutura por objetos que contenham as informações e uma função para imprimir os resultados com seus parametros.
