### ISSUE TITLE
Layout da ficha

### ISSUE THREAD

**Issue by degrecci** [hack-and-slash/gerador-de-goblins-malditos#24]
![referência de ficha](https://user-images.githubusercontent.com/11249408/67726360-5b2b9580-f9c4-11e9-864c-7b58e115e72e.PNG)

A ideia do projeto é virar uma ficha jogável, então os campos de:

- Nível
- Equipamentos
- Vitalidade (A vida decaí durante o jogo, mas pode subir de novo)
- Dano
- Proteção

Abrir PR enviando o layout.
Ps. Caso utilizar fontes (gratuíta pfvr), favor enviar arquivo.

**Comment by victormiguez** [comment]
Opa, essa eu pego! :)
