### ISSUE TITLE
Criar testes unitários

### ISSUE THREAD

**Issue by degrecci** [hack-and-slash/gerador-de-goblins-malditos#8]
Adicionar testes que cubram unitariamente as funções:

- [x] gerarNomeDoGoblin
- [ ] calcularAtributoDeCombate
- [ ] calcularAtributoDeConhecimento
- [ ] calcularAtributoDeHabilidade
- [ ] calcularAtributoDeSorte
- [x] gerarEquipamento

Não é necessario fazer uma PR com todas.

**Comment by pereiraJr** [comment]
#23 Pull request adicionando teste para gerar nome do Goblin.

**Comment by dudevictor** [comment]
Adicionado testes para o método gerarEquipamento #28

**Comment by EmersonManabuAraki** [comment]
#29 Adicionado testes para o método calcularAtributoDeCombate

**Comment by EmersonManabuAraki** [comment]
#31 Adicionado testes para o método calcularAtributoDeConhecimento

**Comment by edumoreira1506** [comment]
#33 Adicionando testes para o método `gerarCaracteristica`
